version: "3.8"
services:
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  
  cadvisor:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/roots:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - ./dev/disk/:/dev/disk:ro
    networks:
      - monitoring
      
  grafana:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana_data:
  
networks: 
  monitoring:
    driver: bridge
