version: "3.8"
services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network
  
  php:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    image: php:8.1-fpm-alpine
    container_name: php
    volumes:
      - ./www:/var/www/html
    networks:
      - network
      
networks: 
  network:
    name: network